// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingPlans.Database;

namespace TrainingPlans.Migrations
{
    [DbContext(typeof(TrainingPlanDbContext))]
    [Migration("20200404215645_InitialWithCompletedWorkouts")]
    partial class InitialWithCompletedWorkouts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrainingPlans.Database.Models.CompletedRepetition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompletedWorkoutId")
                        .HasColumnType("int");

                    b.Property<double?>("DistanceQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("DistanceUom")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedRepetitionId")
                        .HasColumnType("int");

                    b.Property<double?>("RestDistanceQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("RestDistanceUom")
                        .HasColumnType("int");

                    b.Property<double?>("RestTimeQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("RestTimeUom")
                        .HasColumnType("int");

                    b.Property<double?>("TimeQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("TimeUom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompletedWorkoutId");

                    b.HasIndex("PlannedRepetitionId");

                    b.ToTable("CompletedRepetition");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.CompletedWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CompletedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedWorkoutId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlannedWorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedWorkout");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.PlannedRepetition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("DistanceQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("DistanceUom")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PlannedWorkoutId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("RestDistanceQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("RestDistanceUom")
                        .HasColumnType("int");

                    b.Property<double?>("RestTimeQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("RestTimeUom")
                        .HasColumnType("int");

                    b.Property<double?>("TimeQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("TimeUom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlannedWorkoutId");

                    b.ToTable("PlannedRepetition");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.PlannedWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlannedWorkout");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.CompletedRepetition", b =>
                {
                    b.HasOne("TrainingPlans.Database.Models.CompletedWorkout", "CompletedWorkout")
                        .WithMany("CompletedRepetitions")
                        .HasForeignKey("CompletedWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingPlans.Database.Models.PlannedRepetition", "PlannedRepetition")
                        .WithMany()
                        .HasForeignKey("PlannedRepetitionId");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.CompletedWorkout", b =>
                {
                    b.HasOne("TrainingPlans.Database.Models.PlannedWorkout", "PlannedWorkout")
                        .WithMany()
                        .HasForeignKey("PlannedWorkoutId");

                    b.HasOne("TrainingPlans.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.PlannedRepetition", b =>
                {
                    b.HasOne("TrainingPlans.Database.Models.PlannedWorkout", "PlannedWorkout")
                        .WithMany("PlannedRepetitions")
                        .HasForeignKey("PlannedWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingPlans.Database.Models.PlannedWorkout", b =>
                {
                    b.HasOne("TrainingPlans.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
